name: 'Setup Rust Environment'
description: 'Sets up Nix-based Rust environment with caching'

runs:
  using: "composite"
  steps:
    - name: Install Nix with Determinate Systems installer
      uses: DeterminateSystems/nix-installer-action@main
      with:
        determinate: false

    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        use-flakehub: false

    - name: Verify Nix Flake
      shell: bash
      run: nix flake check --no-build
