name: 'OCI Publish'
description: 'Pushes binaries as multi-arch images using clean bash arrays'
inputs:
  bin:
    required: true
  arches:
    required: true
  tags:
    required: true
  registry:
    required: true
  image_name:
    required: true

runs:
  using: "composite"
  steps:
    - name: Push and Manifest
      shell: bash
      run: |
        REFS=""
        DEST="${{ inputs.registry }}/${{ inputs.image_name }}"

        for arch in $(echo '${{ inputs.arches }}' | jq -r '.[]'); do
          DIR="${{ inputs.bin }}-$arch"
          [ ! -f "$DIR/${{ inputs.bin }}" ] && echo "::error::Missing $DIR/${{ inputs.bin }}" && exit 1

          DIGEST=$(tar -C "$DIR" -c "${{ inputs.bin }}" | crane append -f -)
          
          FLAGS=(
            "$DIGEST"
            --entrypoint "/${{ inputs.bin }}"
            --platform "linux/$arch"
            --user "65532:65532"
            --label "org.opencontainers.image.title=${{ inputs.bin }}"
            --label "org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}"
            --label "org.opencontainers.image.revision=${{ github.sha }}"
          )

          FINAL_DIGEST=$(crane mutate "${FLAGS[@]}")
          REFS="$REFS -m $FINAL_DIGEST"
        done

        # 4. Create Multi-Arch Index
        while IFS= read -r tag; do
          [ -n "$tag" ] && crane index append $REFS -t "$tag"
        done <<< "${{ inputs.tags }}"