name: 'OCI Publish'
description: 'Pushes binaries as multi-arch images using clean bash arrays'
inputs:
  bin:
    required: true
  arches:
    required: true
  tags:
    required: true
  registry:
    required: true
  image_name:
    required: true

runs:
  using: "composite"
  steps:
    - name: Push and Manifest
      shell: bash
      run: |
        readarray -t arch_list < <(echo "$ARCHES" | jq -r '.[]')
        while IFS= read -r tag; do
          [ -z "$tag" ] && continue

          REFS=""
          for arch in "${arch_list[@]}"; do
            ARCH_TAG="${tag}-${arch}"
            tar -C "$BIN-${arch}" -c "$BIN" | crane append -f - -t "$ARCH_TAG"
            crane mutate "$ARCH_TAG" --entrypoint "/$BIN" --platform "linux/$arch"

            REFS="$REFS -m $ARCH_TAG"
          done

          crane index append $REFS -t "$tag"
        done <<< "$TAGS"